# Force/Torque sensor
- topic_name: /ft_sensor_data
  ros_type_name: geometry_msgs/msg/Wrench
  gz_type_name: gz.msgs.Wrench
  direction: GZ_TO_ROS

# Operator 1 force/torque sensor
- topic_name: /operator_ft_sensor_data
  ros_type_name: geometry_msgs/msg/Wrench
  gz_type_name: gz.msgs.Wrench
  direction: GZ_TO_ROS

# Operator 1 joint state
- topic_name: /operator_1_joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS

# Operator 1 cmd position (rad)
- ros_topic_name: "/operator_1_cmd_pos"
  gz_topic_name: "operator_1_joint_cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
